-- Add email reply columns to leads table

ALTER TABLE leads
ADD COLUMN IF NOT EXISTS reply_subject VARCHAR(500),
ADD COLUMN IF NOT EXISTS reply_body TEXT,
ADD COLUMN IF NOT EXISTS last_reply_text TEXT,
ADD COLUMN IF NOT EXISTS last_reply_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS booked_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS meeting_link VARCHAR(500),
ADD COLUMN IF NOT EXISTS meeting_notes TEXT;
